---
title: "Does ARK (still) Generate Alpha?"
author: "Martin Geissmann"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: pdf_document
abstract: "Ark Investment has become the largest actively managed ETF provider with innovation/technology-themed funds that delivered great performance. The question one should always ask is if putting your money in any fund will deliver exceptional returns (alpha). We find that all ARK funds delivered a mix of alpha and beta. Above average beta was responsible for the exceptional returns over the past years."
---

```{r init, include=FALSE, echo = F, message=F, warning=F}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
options(knitr.kable.NA = "")
```

```{r}
library(tidyverse)
library(tiqyquant)
library(lubridate)
```

How much Alpha has Cathie Wood generated in her ARK funds?

* ARKK	ARK Innovation ETF	Equity	               $20,167.10[^source]
* ARKG	ARK Genomic Revolution ETF	Equity         	$8,620.88
* ARKW	ARK Next Generation Internet ETF	Equity   	$6,498.44
* ARKF	ARK Fintech Innovation ETF	Equity	        $3,660.54
* ARKQ	ARK Industrial Innovation ETF	Equity      	$3,025.98
* PRNT	3D Printing ETF	Equity	                      $499.39 - passive
* IZRL	ARK Israel Innovative Technology ETF	Equity	$337.52 - passive

[^source]: source AUM as of March 2021: https://etfdb.com/etfs/issuers/ark-investment-management/
